### ISSUE TITLE
Use k8s style YAML objects for job definition

### ISSUE THREAD

**Issue by yuvipanda** [kbatch-dev/kbatch#13]
I really like what I consider the standard definition style for YAML objects in k8s, and it goes something like this:

```
kind: KBatchJob
apiVersion: <lets-you-move-things-around>
metadata:
  name: my-name
  labels: {}
  annotations: {}
spec:
  ...
```

It's a little more verbose, but I think the familiarity + extensibility is worth it. It also means this could become a proper Kubernetes CRD?
